services:
  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-web-server
    networks:
      ctf-corporate-data-breach-net:
        ipv4_address: 172.23.145.45
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-attacker
    networks:
      ctf-corporate-data-breach-net:
        ipv4_address: 172.23.145.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-corporate-data-breach-net:
    name: ctf-corporate-data-breach-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.23.145.0/24
          gateway: 172.23.145.1
